spring:
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource

    # Druid的其他属性配置 springboot3整合情况下,数据库连接信息必须在Druid属性下!
    druid:
      url: jdbc:mysql://localhost:3308/sm_db
      username: root
      password: kafei
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 1
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

  logging:
    level:
      root: debug
  profiles:
    active: dev #激活外部配置application-dev.yaml
      #如果外部配置的key和application key重复 外部的覆盖内部
    #
  web:
    resources:
      static-locations: classpath:/webapp #配置静态资源路径
      #一旦配置，默认的路径 classpath:/META-INF/resources/
#                       classpath:/resources/
#                       classpath:/static/
#                       classpath:/public/  就都不生效了


#mybatis的配置 - 彻底抛弃mybatis-config.xml
#mapperxml文件的位置 settings的配置 别名的配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml    #classpath为resources目录
  type-aliases-package: com.kafei.pojo      #别名的配置
  configuration: #setting的配置
    map-underscore-to-camel-case: true
    automatic-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
mybatis-plus:
#  默认情况下 mapper-locations: classpath:/mapper/*.xml    #classpath为resources目录
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.kafei.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: news_ # 设置表的前缀
#jwt java web token配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义

#  global-config:
#    db-config:
#      id-type: auto # 全局主键策略（auto是自增长，不配置默认是ASSIGN_ID雪花算法，随机生成一个不重复的Long类型数字，若用雪花算法则数据库主键类型设置为BigInt）
#      table-prefix: t_ 全局配置表名前缀
#      logic-delete-field: deleted # 全局逻辑删除的实体类属性名，配置后可以不用在类的属性名添加@TableLogic注解
#    mybatis-plus中不用配置以下驼峰映射，mybatis-plus中该配置默认为true
#    map-underscore-to-camel-case: true
#server:
#  port: 8080
#  servlet:
#    context-path: /